#!/bin/bash

set -e

cd "$(dirname "$0")/.."

function checkout() {
  repo=$1; url=$2; sha=$3

  if [ ! -d "$repo" ]; then
    git clone "https://github.com/$url" "$repo"
  fi

  pushd "$repo"
  git fetch && git reset --hard "$sha"
  popd
}

checkout examples/vyper vyperlang/vyper 886488f715d75f185dfee0d281ee6288411920da
checkout examples/anchor lidofinance/anchor-collateral-steth 4f58604305d4114390b42fc1befaa5e67bfb6858
checkout examples/curve curvefi/curve-contract b0bbf77f8f93c9c5f4e415bce9cd71f0cdee960e


known_failures="$(cat script/known_failures.txt)"

tree-sitter parse -q \
  'examples/**/*.vy' \
  $(for file in $known_failures; do echo "!${file}"; done)

example_count=$(find examples -name '*.vy' | wc -l)
failure_count=$(wc -w <<< "$known_failures")
success_count=$(( $example_count - $failure_count ))
success_percent=$(bc -l <<< "100*${success_count}/${example_count}")

printf \
  "Successfully parsed %d of %d example files (%.1f%%)\n" \
  $success_count $example_count $success_percent
